version: '3'

services:
  # Service Client
  client:
    hostname: client
    build: ./clientws/fastapi_app
    volumes:
      - './clientws/fastapi_app/app:/app'
    ports:
      - '18014:${UVICORN_PORT}'
    environment:
      - 'UVICORN_PORT=${UVICORN_PORT}'
    networks:
      network:
        ipv4_address: '${SERVICE_CLIENT_IP}'
    restart: unless-stopped

  # Service Delivery
  delivery:
    hostname: delivery
    build: ./deliveryws/fastapi_app
    volumes:
      - './deliveryws/fastapi_app/app:/app'
    ports:
      - '18015:${UVICORN_PORT}'
    environment:
      - 'UVICORN_PORT=${UVICORN_PORT}'
    networks:
      network:
        ipv4_address: '${SERVICE_DELIVERY_IP}'
    restart: unless-stopped

  # Service Machine
  machine:
    hostname: machine
    build: ./machinews/fastapi_app
    volumes:
      - './machinews/fastapi_app/app:/app'
    ports:
      - '18016:${UVICORN_PORT}'
    environment:
      - 'UVICORN_PORT=${UVICORN_PORT}'
    networks:
      network:
        ipv4_address: '${SERVICE_MACHINE_IP}'
    restart: unless-stopped

  # Service Order
  order:
    hostname: order
    build: ./orderws/fastapi_app
    volumes:
      - './orderws/fastapi_app/app:/app'
    ports:
      - '18017:${UVICORN_PORT}'
    environment:
      - 'UVICORN_PORT=${UVICORN_PORT}'
    networks:
      network:
        ipv4_address: '${SERVICE_ORDER_IP}'
    restart: unless-stopped

  # Service Payment
  payment:
    hostname: payment
    build: ./paymentws/fastapi_app
    volumes:
      - './paymentws/fastapi_app/app:/app'
    ports:
      - '18018:${UVICORN_PORT}'
    environment:
      - 'UVICORN_PORT=${UVICORN_PORT}'
    networks:
      network:
        ipv4_address: '${SERVICE_PAYMENT_IP}'
    restart: unless-stopped

  haproxy:
    hostname: haproxy
    image: haproxy:2.6-alpine
    ports:
      - '${HAPROXY_PORT}:${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}'
    expose:
      - '${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}'
    networks:
      network:
        ipv4_address: '${HAPROXY_IP}'
    environment:
      - 'SERVICE_CLIENT_IP=${SERVICE_CLIENT_IP}'
      - 'SERVICE_DELIVERY_IP=${SERVICE_DELIVERY_IP}'
      - 'SERVICE_MACHINE_IP=${SERVICE_MACHINE_IP}'
      - 'SERVICE_ORDER_IP=${SERVICE_ORDER_IP}'
      - 'SERVICE_PAYMENT_IP=${SERVICE_PAYMENT_IP}'
      - 'SERVICE_CLIENT_PORT=${UVICORN_PORT}'
      - 'SERVICE_DELIVERY_PORT=${UVICORN_PORT}'
      - 'SERVICE_MACHINE_PORT=${UVICORN_PORT}'
      - 'SERVICE_ORDER_PORT=${UVICORN_PORT}'
      - 'SERVICE_PAYMENT_PORT=${UVICORN_PORT}'
      - 'HAPROXY_PORT=${HAPROXY_PORT}'
      - 'HAPROXY_STATS_PORT=${HAPROXY_STATS_PORT}'
    restart: unless-stopped
    volumes:
      - './apigateway/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'
