version: '3'
services:
  # Service Client
  service1order:
    hostname: order
    build: ./fastapi_app
    volumes:
      - './fastapi_app/app:/app'
    ports:
      - '18014:${UVICORN_PORT}'
    environment:
      - 'UVICORN_PORT=${UVICORN_PORT}'
    networks:
      lb7_network:
        ipv4_address: '${SERVICE1_ORDER_IP}'
    restart: unless-stopped


networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'
