version: '3'
services:
  # Service Client
  service1client:
    hostname: client
    build: ./fastapi_app
    volumes:
      - './fastapi_app/app:/app'
    ports:
      - '18011:${UVICORN_PORT}'
    environment:
      - 'UVICORN_PORT=${UVICORN_PORT}'
    networks:
      lb7_network:
        ipv4_address: '${SERVICE1_CLIENT_IP}'
    restart: unless-stopped
      
networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'
