version: '3'
services:
  # Service Delivery
  service1delivery:
    hostname: delivery
    build: ./fastapi_app
    volumes:
      - './fastapi_app/app:/app'
    ports:
      - '18012:${UVICORN_PORT}'
    environment:
      - 'UVICORN_PORT=${UVICORN_PORT}'
    networks:
      lb7_network:
        ipv4_address: '${SERVICE1_DELIVERY_IP}'
    restart: unless-stopped

networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'
